### ISSUE TITLE
Meeting!

### ISSUE THREAD

**Issue by MysticCat98** [MysticCat98/Maze-Solver-Project#2]
*_# Hey Nate! 
*_
I talked to Zack earlier and neither of us have your information to get in touch with you. If you get this, we were planning to meet on the 3rd floor of the Engineering Building tomorrow at our regular class time. We are going to finish the main portion of the coding process and possibly get as far as we can with a GUI or something. I hope you get this and we will see you there!

**Comment by natemiklas1** [comment]
Ill be there
